# This file is used to set up the parameters for data loading, logging, and other settings.

data_source:
  raw_path: "data/raw/Songs_2025.csv" # Relative or absolute path to data file
  processed_path: "./data/processed/Songs_2025_processed.csv" # Path to save processed data
  type: "csv"                      # Data file type: 'csv' or 'excel'
  delimiter: ","                   # Only used if type == 'csv'
  header: 0                        # Row number to use as column names (0-indexed), update if needed
  encoding: "utf-8"                # File encoding (utf-8 covers most cases)

logging:
  level: "INFO"                         # Logging level: DEBUG (verbose), INFO (default), WARNING, ERROR, CRITICAL
  log_file: "./logs/main.log"    # File path for log output
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"  # Log message format
  datefmt: "%Y-%m-%d %H:%M:%S"          # Date format for logs

data_split:
  test_size: 0.2
  valid_size: 0.2
  random_state: 42

model:
  active:  # Options: logistic_regression, kmeans

  logistic_regression:
    save_path: models/logistic_regression.pkl
    params:

  knn:
    save_path: models/knn.pkl
    params:

features:
  exclude:
    - year
  profiling_variables:
    - track_popularity
    - artist_popularity
    - energy
    - mode
  drop:
    - track_name
    - album
    - artist_name
    - cluster
    - artist_genres
    - year
  audio_features:
    - danceability
    - energy
    - liveness
    - loudness
    - speechiness
    - tempo
    - valence
    - duration_ms
    - artist_popularity
  genre_features:
    - pop
    - rock
    - electronic
    - latin
    - hip-hop
    - indie
    - jazz
    - r&b
    - soul
    - metal
    - classic
    - country
  polynomial:
    audio:
      degree: 2
      include_bias: false
    genre:
      degree: 2
      include_bias: false

target: track_popularity

metrics:

preprocessing:
  drop_columns:
    - instrumentalness
  outlier_removal:
    enabled: true
    features: [duration_ms, track_popularity]
    iqr_multiplier: 1.5
  scale:
    columns: [danceability, energy, loudness, speechiness, acousticness, liveness, valence, tempo, duration_ms, key]
    method: minmax

artifacts:
  metrics_path: models/metrics.json
  preprocessing_pipeline: models/preprocessing_pipeline.pkl
  splits_dir: data/splits
  processed_dir: data/processed

data_validation:
  enabled: true
  action_on_error: "raise"  # options: raise, warn
  report_path: "logs/validation_report.json"
  schema:
    columns:
      - name: "year"
        dtype: "int"
        required: true
        min: 2000
        max: 2025
      - name: "track_name"
        dtype: "str"
        required: true
      - name: "track_popularity"
        dtype: "int"
        required: true
        min: 0
        max: 100
      - name: "album"
        dtype: "str"
        required: true
      - name: "artist_name"
        dtype: "str"
        required: true
      - name: "artist_genres"
        dtype: "str"
        required: true
      - name: "artist_popularity"
        dtype: "int"
        required: true
        min: 0
        max: 100
      - name: "energy"
        dtype: "float"
        required: false
        min: 0.0519
        max: 0.999
      - name: "key"
        dtype: "float"
        required: true
        min: 0.0
        max: 11.0
      - name: "loudness"
        dtype: "float"
        required: true
        min: -56.0
        max: 132.0
      - name: "mode"
        dtype: "float"
        required: true
        min: 0.0
        max: 1.0
      - name: "speechiness"
        dtype: "float"
        required: true
        min: 0.0225
        max: 0.576
      - name: "acousticness"
        dtype: "float"
        required: true
        min: 0.0000129
        max: 0.978
      - name: "instrumentalness"
        dtype: "float"
        required: true
        min: 0.0
        max: 0.985
      - name: "liveness"
        dtype: "float"
        required: true
        min: 0.021
        max: 0.843
      - name: "valence"
        dtype: "float"
        required: true
        min: 0.0377
        max: 0.974
      - name: "tempo"
        dtype: "float"
        required: true
        min: 60.019
        max: 210.857
      - name: "duration_ms"
        dtype: "float"
        required: true
        min: 97393.0
        max: 688453.0
      - name: "danceability"
        dtype: "float"
        required: true
        min: 0.0
        max: 1.0
