name: group8_full

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas
  - numpy
  - openpyxl
  - pyyaml
  - python-dotenv
  - pytest
  - pytest-dotenv
  - scikit-learn
  - statsmodels
  - joblib
  - matplotlib
  - seaborn
  - scipy
  - pip

  - pip:
      - pytest-cov
      - black
      - flake8
      - hydra-core
      - mlflow
      - wandb
      - fastapi
      - uvicorn
      - pydantic
