name: group8_full

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas
  - numpy
  - openpyxl
  - pyyaml
  - python-dotenv
  - pytest
  - pytest-dotenv
  - scikit-learn=1.5.1
  - statsmodels
  - joblib
  - matplotlib
  - seaborn
  - scipy=1.11
  - pip
  - fastapi
  - uvicorn


  - pip:
      - pytest-cov
      - black
      - flake8
      - hydra-core
      - mlflow
      - wandb
      - fastapi
      - uvicorn
      - pydantic
      - joblib
      - pydantic

