name: CI Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: group8_full
        auto-activate-base: false
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda info
        conda list
        
    - name: Run tests with coverage
      shell: bash -l {0}
      run: |
        pytest -q --cov=src --cov-report=term-missing --cov-fail-under=75
        
    - name: Run linting
      shell: bash -l {0}
      run: |
        flake8 . --exit-zero
        
    - name: Run MLflow pipeline
      shell: bash -l {0}
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        MLOPS_ENV: ${{ secrets.MLOPS_ENV }}
        WANDB_MODE: offline
      run: |
        mlflow run . --no-conda
