name: CI Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: conda.yaml
        activate-environment: mlops_group8
        auto-activate-base: false
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda info
        conda list
        
    - name: Run MLflow pipeline
      shell: bash -l {0}
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        MLOPS_ENV_STAGING: ${{ secrets.MLOPS_ENV_STAGING }}
        WANDB_MODE: offline
      run: |
        mlflow run . --no-conda
